-- Seed de catalogo vehiculos
-- Ejecutar despues de aplicar migraciones:
-- mysql -u <usuario> -p <basedatos> < prisma/seed_vehiculos.sql

START TRANSACTION;

INSERT INTO `vehiculos` (`class`, `nombre`, `tipo`)
VALUES
  (100000, 'No definido', NULL),
  (6, 'Pick up Doble cabina Mitsubishi L200 Sportero', NULL),
  (26, 'Pick up doble cabina Mahindra Scorpio (Cafe)', NULL),
  (42, 'Microbus Kia Blanco Pregio (Mov. Personal CISA)', NULL),
  (45, 'Panelito Chevrolet CMV. Busito Blanco (esta en Utila, primer electrico)', NULL),
  (47, 'Panelito Chevrolet CMV. Busito Blanco (esta en Utila, segundo electrico)', NULL),
  (55, 'Camion Mitsubishi Canter. (el que esta en taller electrico, area de llantas, el q', NULL),
  (63, 'Turismo Chrysler PT Cruiser', NULL),
  (65, 'Camioneta Toyota Prado Beige Land Cruiser', NULL),
  (83, 'Pick up Doble cabina Volkswagen Amarok', NULL),
  (84, 'Amarok blanco', NULL),
  (93, 'Tricimoto Yumbo Cargo 200', NULL),
  (96, 'Turismo Nissan Leaf GRIS TEGUCIGALPA', NULL),
  (97, 'Pick up doble cabina Toyota Hilux Ing. Luis Elejalde', NULL),
  (98, 'Pick up doble cabina Toyota Hilux Ing. Danielle Toffanello', NULL),
  (138, 'Camion blanco Isuzu (tiene un problema legal, fue desarmado y esta en el area', NULL),
  (139, 'Camion Isuzu NPR71H-22', NULL),
  (143, 'Lowboy Fruehauf (el Chasis, que se deja en Plantel de FerreHogar)', NULL),
  (144, 'Highboy Utility Flat', NULL),
  (155, 'Contenedor/Remolque Oshkosh', NULL),
  (159, 'Chasis Cheetah (amarillo que sostiene el contenedor de 20 pies)', NULL),
  (180, 'Camion Isuzu NPR71H-22', NULL),
  (194, 'Motocicleta Scooter Yamaha YW-100CF', NULL),
  (303, 'Turismo Nissan Leaf (azul) esta en taller electrico', NULL),
  (304, 'Turismo Nissan Leaf (blanco) esta en La Ceiba', NULL),
  (306, 'Pick up Doble cabina Nissan NP300 FRONTIER', NULL),
  (307, 'Pick up Doble cabina Mitsubishi L-200', NULL),
  (308, 'CAMION KIA DOBLE CABINA', NULL),
  (310, 'FORD 450', NULL),
  (311, 'AMAROK GRIS METALICO ING ARLEN', NULL),
  (312, 'CARRITO DE GOLF BLANCO', NULL),
  (313, 'CARRITO DE GOLF GRIS', NULL),
  (314, 'CARRITO DE GOLF BLANCO', NULL),
  (315, 'CARRITO DE GOLF BEIGE', NULL),
  (316, 'Camioneta land cruiser prado bronce metalico', NULL),
  (317, 'NISSAN NV 200 2019', NULL),
  (318, 'NISSAN NV 200 2015', NULL),
  (319, 'CARRITO DE GOLF', NULL),
  (320, 'MONTAGARCAS', NULL),
  (321, 'MITSUBISHI MONTERO SPORT CAMIONETA BRONCE METALICO', NULL),
  (322, 'NISSAN NV 200 PANEL BLANCO', NULL),
  (323, 'MITSUBISHI MONTERO SPORT CAMIONETA BRONCE METALICO', NULL),
  (324, 'NISSAN NV 200 PANEL COLOR AZUL', NULL),
  (400, 'Retroexcavadors John Deere 310SE ano 1999', NULL),
  (401, 'Bus International CE', NULL),
  (402, 'Camion Plataforma International 4300 SBA', NULL),
  (403, 'Bus International CE', NULL),
  (404, 'Cabezal peterbilt', NULL),
  (405, 'Cabezal kenworth', NULL),
  (406, 'Plataforma lufkin', NULL),
  (407, 'Plataforma AZTEC', NULL),
  (408, 'Remolque o chasis amarillo', NULL),
  (409, 'EXCAVADORA KOBELCO 2006', NULL),
  (410, 'REMOLQUE O CHASIS AMARILLO 40FT UPCO', NULL),
  (411, 'REMOLQUE MARCA ALLI', NULL),
  (14, 'Pick up cabina sencilla Mazda 2500', NULL),
  (44, 'Pick up cabina sencilla Nissan Frontier', NULL),
  (69, 'Camion cabina sencilla Kia K2700', NULL),
  (74, 'Pick up Doble cabina Mahindra Scorpio', NULL),
  (94, 'Rhino', NULL),
  (110, 'Excavadora John Deere 270DLC', NULL),
  (113, 'Forklift JLG Skytrack 6036', NULL),
  (114, 'Cargadora John Deere 544H', NULL),
  (119, 'Vibrocompactador Ingersoll SD45D', NULL),
  (120, 'Volqueta White GMC Autocar', NULL),
  (123, 'Volqueta GMC C7500', NULL),
  (187, 'Motoniveladora CAT 140M', NULL),
  (188, 'Water track international 2000 gal.', NULL),
  (189, 'Retroexcavadora John Deere 310SG', NULL),
  (195, 'US Military rough terrain tractor', NULL),
  (291, 'MiniCargadora CASE 60XT', NULL),
  (302, 'Cuatrimoto Kawasaki KRF750L9FA', NULL),
  (309, 'Mitsubishi Montero Ocre', NULL),
  (906, 'Lancha MISTAKEN', NULL),
  (907, 'Lancha color aluminio', NULL)
ON DUPLICATE KEY UPDATE
  `nombre` = VALUES(`nombre`),
  `tipo` = VALUES(`tipo`);

COMMIT;
